
Import('pkg baseEnv')

env = baseEnv.Copy()
env.Append(CPPPATH = Split('# #test'),
           LIBPATH = ['#cppdom'],
           LIBS = ['cppdom'])

tests = Split("""
   equaltest
   maketree
   nodetest
   parsetest
   predtest
""")

for t in tests:
   prog = pkg.createProgram(t, env)
   prog.addSources([t+'.cpp'])
