#!python
Import('*')

import os
pj = os.path.join

test_env = build_env.Copy()
test_env.Append(CPPPATH = [inst_paths['include'], '#test'],
                LIBPATH = [inst_paths['lib'],],
                LIBS = [cppdom_app_libname])

tests = Split("""
   maketree
   nodetest
   parsetest
""")

if "shared" in combo["libtype"]:
   test_env.AppendUnique(CPPDEFINES = ["CPPDOM_DYN_LINK"])

for t in tests:
   test_prog = test_env.Program(t, t+'.cpp')

subdirs = []
if cppunit_options.isAvailable():
   subdirs.append('suite')
SConscript(dirs = subdirs)
