Import('baseEnv')
Import('GetPlatform SetupCppUnit')
Import('buildDir')
Import('PREFIX')

import os
pj = os.path.join

sources = Split("""
   runner.cpp
   TestCases/ErrorTest.cpp
   TestCases/ParseTest.cpp
   TestCases/PredTest.cpp
   TestCases/SpiritTest.cpp
""")

env = baseEnv.Copy()
env.Append(CPPPATH = ["#", "."],
           LIBPATH = [pj('#', buildDir, 'cppdom')],
           LIBS    = ['cppdom'])
SetupCppUnit(env)

# Win32 doesn't have libdl
if GetPlatform() != 'win32':
   env.Append(LIBS = Split('dl'))

if GetPlatform() == 'linux':
   env.Append(CXXFLAGS = ['-fexceptions'])

env.Program('runner', sources)
