#!python
Import('*')

import os
pj = os.path.join

sources = Split("""
   runner.cpp
   TestCases/ErrorTest.cpp
   TestCases/NodeTest.cpp
   TestCases/ParseTest.cpp
   TestCases/PredTest.cpp
   TestCases/OptionRepositoryTest.cpp
""")

if boost_options.isAvailable():
   sources.append("TestCases/SpiritTest.cpp")

env = baseEnv.Copy()
env.Append(CPPPATH = [inst_paths['include'], '#test', pj('#test','suite')],
                LIBPATH = [inst_paths['lib'],],
                LIBS = [cppdom_app_libname])

cppunit_options.apply(env)

# Win32 doesn't have libdl
if GetPlatform() != 'win32':
   env.Append(LIBS = Split('dl'))

test_prog = env.Program('runner', sources)
