#!python
Import('baseEnv', 'GetPlatform', 'buildDir', 'cppdom_pkg')
Import('cppunit_options', 'boost_options')

import os
pj = os.path.join

sources = Split("""
   runner.cpp
   TestCases/ErrorTest.cpp
   TestCases/NodeTest.cpp
   TestCases/ParseTest.cpp
   TestCases/PredTest.cpp
   TestCases/OptionRepositoryTest.cpp
""")

if boost_options.isAvailable():
   sources.append("TestCases/SpiritTest.cpp")

env = cppdom_pkg.getEnv().Copy()
env.Append(CPPPATH = ["#", "."],
           LIBPATH = [pj('#', buildDir, 'cppdom')],
           LIBS    = ['cppdom'])
cppunit_options.updateEnv(env)

# Win32 doesn't have libdl
if GetPlatform() != 'win32':
   env.Append(LIBS = Split('dl'))

if GetPlatform() == 'linux':
   env.Append(CXXFLAGS = ['-fexceptions'])

test_prog = cppdom_pkg.createProgram('runner', env, 'test/cppdom')
test_prog.addSources(sources)
test_prog.build()
