#!python
Import('*')

import os
pj = os.path.join

test_env = baseEnv.Copy()
test_env.Append(CPPPATH = [inst_paths['include'], '#test'],
                LIBPATH = [inst_paths['lib'],],
                LIBS = ['cppdom'])

tests = Split("""
   maketree
   nodetest
   parsetest
""")

for t in tests:
   test_prog = test_env.Program(t, t+'.cpp')

subdirs = []
if cppunit_options.isAvailable():
   subdirs.append('suite')
SConscript(dirs = subdirs)
