
Import('baseEnv')

env = baseEnv.Copy()
env.Append(CPPPATH = ['#', '#test'])
env.Append(LIBPATH = ['#cppdom'])
env.Append(LIBS = ['cppdom'])

tests = Split("""
   nodetest
   parsetest
   predtest
""")

for t in tests:
   env.Program(t, t+'.cpp')
