#!/bin/sh
dirs=../../cppdom

CPP_EXTS=java,h.in,h,cxx,cpp
HASH_EXTS=in,pl,sh,py

#------------------------------------------------------------------------------
# You shouldn't have to modify anything past this line.
#------------------------------------------------------------------------------
COPY_DATA_CPP=data/copyright.c.txt
COPY_DATA_HASH=data/copyright.hash.txt
COPY_CONFIG_CPP=config/copyright-replace.c.pl
COPY_CONFIG_HASH=config/copyright-replace.hash.pl

MODELINE_FILE=config/modeline-replace.c.pl

# All the projects
for d in $dirs; do
  auto-copyright.pl -d $d -e $CPP_EXTS -c $COPY_DATA_CPP -t $COPY_CONFIG_CPP -m $MODELINE_FILE -a;
  auto-copyright.pl -d $d -e $HASH_EXTS -c $COPY_DATA_CPP -t $COPY_CONFIG_CPP -a;
done
